remove old lease impl in hub side
open-cluster-management/multicluster-observability-operator pull request #475
Opened 2021-04-21 17:20 UTC by marcolan018

Signed-off-by: Marco <llan@redhat.com>

2021-04-22 04:50 UTC, marcolan018 commented
/retest

2021-04-22 04:55 UTC, clyang82 requested changes

2021-04-22 04:55 UTC, clyang82 commented on controllers/placementrule/endpoint_metrics_operator.go
> +	container.Image = "blue0/endpoint-monitoring-operator:0.1.0"
This is for testing. need to remove.

2021-04-22 05:00 UTC, marcolan018 commented on controllers/placementrule/endpoint_metrics_operator.go
> +	container.Image = "blue0/endpoint-monitoring-operator:0.1.0"
@clyang82 
removed

2021-04-22 05:14 UTC, clyang82 commented
/lgtm

2021-04-22 06:18 UTC, clyang82 commented
/lgtm

2021-04-22 07:36 UTC, clyang82 commented
/retest

2021-04-22 13:55 UTC, clyang82 commented
/retest

2021-04-22 17:17 UTC, marcolan018 commented
/retest

2021-04-23 01:16 UTC, morvencao commented
/test test-e2e

2021-04-23 11:12 UTC, clyang82 commented
/lgtm

2021-04-23 11:20 UTC, merged